# Generated by Django 3.2.6 on 2021-09-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210915_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Up Vote'), ('Down', 'Down Vote')], max_length=250),
        ),
    ]
